- name: variables
  hosts: local
  connection: local
  vars: #play local veriables
   COURSE: DevOps with AWS
   DURATION: 120hrs
   TRAINER: sivakumar
  tasks:
   - name: print the variable
     ansible.builtin.debug:
       msg: " course is {{ COURSE }}, Duration is {{ DURATION }}, trainer {{ TRAINER }}"