- name: variables
  hosts: local
  connection: local
  vars: #play local veriables global variables can be defined in inventory.ini file
   COURSE: "DevOps with AWS"
   DURATION: 120hrs
   TRAINER: sivakumar
  tasks:
  - name: print the variable
    vars: 
       COURSE: ansible
       ansible.builtin.debug:
        msg: " course is {{ COURSE }}, Duration is {{ DURATION }}, trainer {{ TRAINER }}"
     
  - name: print the variable
    ansible.builtin.debug:
       msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, trainer {{ TRAINER }}"  