- name: variables from files
  hosts: local
  connection: local
  vars-promt:
  - name: COURSE
    promt: please enter course name
  - name: DURATION
    promt: please enter course duration
  - name: TRAINER
    promt: please enter trainer name
  tasks:
   - name: print course information
     ansible.builtin.debug:
       msg: "course is {{ COURSE }}, duration is: {{ DURATION }}, trainer is: {{ TRAINER }}"